language: php

php:
  - 8.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs

install:
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover coverage.clover
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
